version: "3.8"
services:
  app:
    image: app:django
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    container_name: django_container
    command: >
      bash -c '
        nohup python3 manage.py tailwind start &
        python3 manage.py runserver 0.0.0.0:8000
      '
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: An1a-Am1pe-a0aj1
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
