version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    ports:
      - 8000:8080
    depends_on:
      - app
    networks:
      - app-nw
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: An1a-Am1pe-a0aj1
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - db-nw
    ports:
      - 3306:3306
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/django
    ports:
      - 8080:8000
    command: >
      bash -c '
        python3 uwsgiconfig.py --build &&
        nohup python3 manage.py tailwind start &
        uwsgi --socket :8080 --module app.wsgi --py-autoreload 1 --logto /tmp/tmp.log
      '
    networks:
      - app-nw
      - db-nw
networks:
  app-nw:
  db-nw:
